# docker-compose.yml file
version: '3'
services:
  # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.config:/etc/nginx/nginx.config
    ports:
      - "8080:80"

  # The web server1
  server1:
    image: nginx:1.16.0-alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
