# docker-compose.yml file
version: '3'
services:
  # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    ports:
      - "8080:80"

  # The web server1
  server1:
    image: nginx:1.16.0-alpine
    volumes:
      - ./:/usr/share/nginx/html
